### ISSUE TITLE
Userクラスのカプセル化

### ISSUE THREAD

**Issue by iizuka-youhei** [zto-michishita/play-zero-training#10]
https://github.com/zto-michishita/play-zero-training/blob/ef01ec03e0b0fe09f54a6962775c20583a24f519/app/models/User.java#L12-L48

[must]
Userクラスですがフィールド変数が全てpublicになっていてゲッターとセッターメソッドを入れている意味が無いように思えます。また、idについては外部から値を変更できては困るのでprivateにしてゲッターのみのほうが安全だと思います。

**Comment by zto-michishita** [comment]
Playの標準の機能(勝手にカプセル化してゲッターセッターを付ける)を切ってから、変更しておりませんでした。

PRお願いします。

**Comment by zto-michishita** [comment]
#12
