### ISSUE TITLE
編集ページに最初から値を入れたほうが良いです。

### ISSUE THREAD

**Issue by iizuka-youhei** [zto-michishita/play-zero-training#6]
https://github.com/zto-michishita/play-zero-training/blob/a3cf9d1a6d55b1996620f14ce3242533e353242e/app/controllers/FormController.java#L52-L60

[must]
編集ページに行ったときにすでにフォームに入力された値が入っている状態の方が好ましいのでfillメソッドでフォームに値をセットしましょう。
ドキュメント：[https://www.playframework.com/documentation/2.8.x/JavaForms#Filling-a-form-with-initial-default-values](https://www.playframework.com/documentation/2.8.x/JavaForms#Filling-a-form-with-initial-default-values)

例：

```
        if(id != null && User.finder.byId(id) != null) {
            this.updateUser = User.finder.byId(id);
            UpdateForm form = new UpdateForm();
            form.setName(this.updateUser.name);
            form.setText(this.updateUser.text);
            System.out.println(form.getText());
            Form<UpdateForm> formdata = updateForm.fill(form);
            return ok(views.html.fix.render(updateUser, formdata, request, messagesApi.preferred(request)));
        }
```

**Comment by zto-michishita** [comment]
ご指摘ありがとうございます！

確かにそのとおりだと思います。
いまのままでは、Form欄の名前で何を入力するのかを推測するしかないので、値が入れてあったほうがユーザーはわかりやすいと思います。

PRお願いします。

**Comment by iizuka-youhei** [comment]
PRしました！

**Comment by zto-michishita** [comment]
見ます

**Comment by zto-michishita** [comment]
#9
