### ISSUE TITLE
Formクラスの名前について

### ISSUE THREAD

**Issue by iizuka-youhei** [zto-michishita/play-zero-training#8]
[must]
FormクラスにCreateForm.java、UpdateForm.java、DeleteForm.javaとありますが、今後機能を増やしてフォームが増えたときに何のフォームなのかがわからなくなるので名前を変えるべきだと思います。

https://github.com/zto-michishita/play-zero-training/blob/345771ea5f644d7c09742e5f1a2fe64177c6efcc/app/models/UpdateForm.java#L1-L5
[imo]
CreateFormを継承しているだけなのでUpdateFormはそもそも必要ないと思います。

**Comment by zto-michishita** [comment]
> FormクラスにCreateForm.java、UpdateForm.java、DeleteForm.javaとありますが、今後機能を増やしてフォームが増えたときに何のフォームなのかがわからなくなるので名前を変えるべきだと思います。

ご指摘されて気づきました…そのとおりだと思います。
変えるとすれば頭にBoardを付けると良いのかなと思います。
例
BoardCreateForm.java

> CreateFormを継承しているだけなのでUpdateFormはそもそも必要ないと思います。

これは賛同できません。

本来ならForm.javaをInterfaseかabstractで作成し、それをExtendsしていく作り方が一番良いと思われるのですが、DeleteFormだけ他のFormと違い、IDだけを入力するFormなので、他のFormと整合性が取れなかったので、UpdateFormはCreateFormをExtendsしています。また、同じメソッド、同じフィールドを持つものを２つ作るのは冗長だと思ったので、UpdateFormはCreateFormをExtendsしています。

CreateFormとUpdateFormは同一のメソッドとフィールドを持っていますが、それをコントローラー側で使うときには、分けられていたほうがわかりやすい上、ファイル名とインスタンス名で何がしたいかを推測できます。ファイルは増えるますが、理解しやすさが段違いなので、UpdateFormは要ると思います

**Comment by iizuka-youhei** [comment]
了解しました。
Formクラスの名前を変更してPRします。

**Comment by zto-michishita** [comment]
ありがとうございます。
お願いします。

**Comment by iizuka-youhei** [comment]
PRしました！
